# Generated by Django 5.2.8 on 2025-11-27 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
