# Generated by Django 5.2.8 on 2025-11-18 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(default='images/defult.png', upload_to='plants/images/')),
                ('category', models.CharField(choices=[('MED', 'Medicinal'), ('ORN', 'Ornamental'), ('ARO', 'Aromatic'), ('FRT', 'Fruit Plants'), ('TOX', 'Toxic Plants'), ('IN', 'Indoor Plants'), ('OUT', 'Outdoor Plants')], max_length=150)),
                ('is_edible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
