# Generated by Django 5.2.8 on 2025-11-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('succulent', 'Succulent'), ('herb', 'Herb')], max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
