# Generated by Django 5.2.8 on 2025-11-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='plants/images/'),
        ),
    ]
