# Generated by Django 5.2.8 on 2025-11-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('tree', 'Tree'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('flower', 'Flower'), ('herb', 'Herb'), ('succulent', 'Succulent')]),
        ),
    ]
