# Generated by Django 5.2.8 on 2025-11-19 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='native_to',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='used_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
