# Generated by Django 5.2.8 on 2025-11-19 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='native_to',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
