# Generated by Django 5.2.8 on 2025-11-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='country_of_origin',
            field=models.CharField(blank=True, help_text='The country where this plant originates.', max_length=100, null=True, verbose_name='Country of Origin'),
        ),
    ]
