# Generated by Django 5.2.8 on 2025-11-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_plant_country_of_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='country_of_origin',
        ),
        migrations.AddField(
            model_name='plant',
            name='native_to',
            field=models.CharField(blank=True, help_text='Country or region where this plant is native to.', max_length=150),
        ),
    ]
