# Generated by Django 5.2.8 on 2025-11-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='default@planteer.com', max_length=254),
            preserve_default=False,
        ),
    ]
