# Generated by Django 5.2.8 on 2025-11-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries/flags/')),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.RemoveField(
            model_name='plant',
            name='native_to',
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='native_plants', to='plants.country'),
        ),
    ]
