# Generated by Django 5.2.8 on 2025-11-23 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(to='plants.category'),
        ),
    ]
