# Generated by Django 5.2.8 on 2025-11-22 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_reviw'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='reviw',
            new_name='Review',
        ),
    ]
