# Generated by Django 5.2.8 on 2025-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0004_plant_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('flag', models.ImageField(default='images/default_flag.jpg', upload_to='plants/images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='categories',
        ),
        migrations.AddField(
            model_name='plant',
            name='Countries',
            field=models.ManyToManyField(to='plants.country'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
