# Generated by Django 5.2.8 on 2025-11-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0005_country_remove_plant_categories_plant_countries_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='Countries',
            new_name='countries',
        ),
    ]
