# Generated by Django 5.2.8 on 2025-11-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_delete_plant'),
        ('plants', '0006_plant_countries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='countries.country'),
        ),
    ]
