# Generated by Django 5.2.8 on 2025-11-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0006_rename_countries_plant_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='countries',
            new_name='Countries',
        ),
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=models.ImageField(default='media/images/default_flag.jpeg', upload_to='plants/images/'),
        ),
    ]
