# Generated by Django 5.2.8 on 2025-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0007_delete_country_alter_plant_countries'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='watering',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', max_length=64),
        ),
    ]
