# Generated by Django 5.2.8 on 2025-11-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plant',
        ),
    ]
