# Generated by Django 5.2.8 on 2025-11-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='image',
        ),
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(),
        ),
    ]
