# Generated by Django 5.2.8 on 2025-11-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('ornamental', 'Ornamental'), ('monocots', 'Monocots'), ('Herbaceous', 'Herbaceous Angiosperms'), ('Woody', 'Woody Angiosperms')]),
        ),
    ]
