# Generated by Django 5.2.8 on 2025-11-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_alter_plant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
