# Generated by Django 5.2.8 on 2025-11-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plant", "0003_category_alter_plant_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("flag", models.ImageField(upload_to="flags/")),
            ],
            options={
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.AddField(
            model_name="plant",
            name="native_countries",
            field=models.ManyToManyField(related_name="plants", to="plant.country"),
        ),
    ]
