# Generated by Django 5.2.8 on 2025-11-20 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='title',
            new_name='name',
        ),
    ]
