# Generated by Django 5.2.8 on 2025-11-19 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0005_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flowering', 'Flowering'), ('succulents', 'Succulents'), ('shade', 'Shade'), ('trees', 'Trees')]),
        ),
    ]
