# Generated by Django 5.2.8 on 2025-11-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_alter_plant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flowering', 'Flowering'), ('succulents', 'Succulents'), ('trees', 'Trees')]),
        ),
    ]
