# Generated by Django 5.2.8 on 2025-11-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0006_rename_title_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('flag', models.ImageField(upload_to='flags/')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plant.country'),
        ),
    ]
