# Generated by Django 5.2.8 on 2025-11-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
