# Generated by Django 5.2.8 on 2025-11-23 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0009_remove_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('flowering', 'Flowering'), ('succulents', 'Succulents'), ('trees', 'Trees')])),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
    ]
