# Generated by Django 5.2.8 on 2025-11-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0010_category_remove_plant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='categories',
            field=models.ManyToManyField(to='plant.category'),
        ),
    ]
