# Generated by Django 5.2.8 on 2025-11-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0011_plant_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(choices=[('flowering', 'Flowering'), ('succulents', 'Succulents'), ('trees', 'Trees')], max_length=50),
        ),
    ]
