# Generated by Django 5.2.8 on 2025-11-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0012_alter_category_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2048)),
                ('image', models.ImageField(default='images/flags.png', upload_to='images/')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='countries',
            field=models.ManyToManyField(to='plant.country'),
        ),
    ]
