# Generated by Django 5.2.8 on 2025-11-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0013_country_plant_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='countries',
            new_name='countories',
        ),
    ]
