# Generated by Django 5.2.8 on 2025-11-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0014_rename_countries_plant_countories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='countories',
            new_name='countries',
        ),
    ]
