# Generated by Django 5.2.8 on 2025-11-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0015_rename_countories_plant_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='categories',
        ),
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.CharField(choices=[('flowering', 'Flowering'), ('succulents', 'Succulents'), ('trees', 'Trees')], default='flowering', max_length=50),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
