# Generated by Django 5.2.8 on 2025-11-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('used_for', models.TextField()),
                ('image', models.ImageField(upload_to='plants/')),
                ('category', models.CharField(choices=[('house', 'House Plant'), ('outdoor', 'Outdoor'), ('herb', 'Herb'), ('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('other', 'Other')], default='other', max_length=20)),
                ('is_edible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
