# Generated by Django 5.2.8 on 2025-11-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
