# Generated by Django 5.2.8 on 2025-11-18 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-sent_at'], 'verbose_name': 'رسالة اتصال', 'verbose_name_plural': 'رسائل الاتصال'},
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='created_at',
            new_name='sent_at',
        ),
    ]
